# Generated by Django 2.0.5 on 2018-07-27 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('prerequisites', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Course')),
            ],
        ),
    ]
