# Generated by Django 2.0.5 on 2018-07-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180727_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='prereqs', to='main.Course'),
        ),
    ]
